# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text=b'Title of poem', max_length=400)),
                ('author', models.CharField(db_index=True, help_text=b'Title of poem', max_length=400)),
                ('date_selected', models.DateTimeField(auto_now_add=True, db_index=True, help_text=b'UTC timestamp of when poem was selected')),
                ('lines', models.TextField(help_text=b'Lines of poem')),
                ('lines_count', models.PositiveIntegerField(db_index=True, help_text=b'Number of lines in poem')),
            ],
        ),
    ]
