# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-01-12 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_per_day', '0002_auto_20220112_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date_selected',
            field=models.DateField(auto_now_add=True, db_index=True, help_text=b'Date of when poem was selected', unique=True),
        ),
    ]
