# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_per_day', '0003_auto_20220112_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.CharField(db_index=True, help_text=b'Author of poem', max_length=400),
        ),
    ]
